### ISSUE TITLE
[1.14.3] Ruins -Clients crash when breaking anything on a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [AtomicStryker/atomicstrykers-minecraft-mods#271]
Client crashlog - 
https://gist.github.com/ProsperCraft/e1fe4d3c80587e4e7525ba53a7d938ab

Reproduced here -
https://gist.github.com/ProsperCraft/ca53c1ab32aa16b8aefa75a57158442e

ruins-1.14.3
forge-1.14.3-27.0.25

**Comment by AtomicStryker** [comment]
Aye, thanks for reporting. I need to add a clientside exclusion to the code ... done https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/9ab153f4f28d70417a708d967828d5c691ef57d8

I have pushed a build with the fix to curse. Try again

**Comment by ProsperCraft** [comment]
I think you forgot to increment the version number, so it will bugger up client updates.

**Comment by AtomicStryker** [comment]
I don't have to increment version numbers when there is no change to compatibility.

That being said i don't have any versioning for 1.13 and later right now. I suppose i could use the .toml file

**Comment by ProsperCraft** [comment]
This is an example of the problem -

![035a6e30692e752a612078c7fcbb7673](https://user-images.githubusercontent.com/4427684/60773193-477bbc80-a0bf-11e9-96e7-800c20c03a03.png)

**Comment by ProsperCraft** [comment]
The launcher sees no difference between the two files, so it won't show that the client needs an update.

**Comment by ProsperCraft** [comment]
The original issue was fixed, but the version numbers still being the same are causing issues still.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/c736eab41acb9ce7c37f0bd8a2e0133f16710640
I have pushed a build to curse which has actual versioning as far as forge is concerned

**Comment by ProsperCraft** [comment]
Both issues fixed thank you.  Please consider adding version numbers to the file name for ease of doing updates though.
