### ISSUE TITLE
Crashing with Vault Hunters 3.11 [1.18.2]

### ISSUE THREAD

**Issue by spikespaz** [AtomicStryker/atomicstrykers-minecraft-mods#480]
Having this mod causes the server to crash after hanging for `max-tick`, a few seconds after entering a vault.
[crash-2023-08-17_22.03.42-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/12375575/crash-2023-08-17_22.03.42-server.txt)

**Comment by AtomicStryker** [comment]
Aye, the block regeneration was global rather than world/dimension specific, and could crash like this. I pushed fixed versions to curse for 1.18, 1.19 and 1.20

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/32507c973de79faa427332ef9acff62e3f2d9833
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/e668e733e722d6de3649c59152593e96e4bf3730
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/4d543ea8aad53b39c7c3526ddf30b7db7d9e147b

**Comment by spikespaz** [comment]
Thank you, will close the issue when confirmed resolved.

**Comment by spikespaz** [comment]
That did not fix the issue, and this time there was no crash log. I have the latest 1.18.7 version for MC 1.18. I entered the Nether this time, instead of a vault, and when the game crashed I removed the mod to confirm it as the culprit.

**Comment by spikespaz** [comment]
Is there any information that I can provide to help you figure out what the issue may be?

**Comment by spikespaz** [comment]
I have added a number of mods to the pack.

- `balm-3.2.6.jar` (updated)
- `trashslot-forge-1.18.2-11.0.3.jar` (new)
- `collective-1.18.2-6.65.jar` (new)
- `stackrefill-1.18.2-4.0.jar` (new)
- `FallingTree-1.18.2-3.5.5.jar` (new)
- `MultiMine-1.18.7.jar` (new, culprit)
- `MouseTweaks-forge-mc1.18-2.22` (new)
- `configured-2.0.1-1.18.2.jar` (new, optional for JEI)
- `soundphysics-forge-1.18.2-1.0.6.jar` (new)
- `smoothswapping-0.9.1-1.18.2-forge.jar` (new)
- `PresenceFootsteps-1.18.2-1.5.1-forge` (new)
- `dynamiclightsreforged-1.18.2_v1.3.3.jar` (new)
- `rubidium_extras-1.18.2_v1.3.2.jar` (new)

**Comment by AtomicStryker** [comment]
Well, what is the minimal setup to reproduce it? Does it happen when you have just my mod and enter the nether?
Does it always happen or do you do something specific (like having regenerating blocks?)
Try disabling block regeneration in the config file
You can also enable debug in the config file, a lot of info will be printed to the logfiles

**Comment by spikespaz** [comment]
This is really weird. I bisected the mods, even some of the ones in the pack that I thought might matter, and couldn't get it to crash. But then, after playing for a while, it crashed again with no log.

Note that it did crash while breaking Netherrack really fast, and I think it may have run out of memory because it was near the upper limit for my server host (9 GiB). You might want to check that the new implementation using `HashMap` isn't leaking.

Strange. I guess I will close this and re-open if I have proof that Multi Mine is still culprit.

Thanks for the quick fix!
