### ISSUE TITLE
can't translate

### ISSUE THREAD

**Issue by wsxiya** [AtomicStryker/atomicstrykers-minecraft-mods#482]
When I tried to translate this mod, I found that the name of the creature could not be translated successfully. I tried to change all the language files, but none of them took effect
![3Y$B28%PS$E (IF1(_ K9SL](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/114494454/d1032028-c884-4b64-9c3c-da2856a4bbbc)
![7L_(%F)Y65TDC4{II06XNQW](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/114494454/7baf0196-a9b2-463a-9346-319af18002e9)

**Comment by wsxiya** [comment]
The mod version is the latest version of 1.19.2

**Comment by AtomicStryker** [comment]
Try changing entity key to lowercase string

like translation.infernalmobs:entity.zombie

**Comment by wsxiya** [comment]
Thanks, I'll try it now

**Comment by wsxiya** [comment]
> 尝试将实体键更改为小写字符串
> 
> 喜欢翻译.地狱暴徒：实体.僵尸

Thanks, I'll try it now

**Comment by wsxiya** [comment]
> 尝试将实体键更改为小写字符串
> 
> 喜欢翻译.地狱暴徒：实体.僵尸

It can be translated if changed to lowercase, thank you very much!

**Comment by AtomicStryker** [comment]
This had been fixed for 1.20, i pushed a new version for 1.19 fixing this also
The old style i18n config with uppercase should work again after update

**Comment by wsxiya** [comment]
> 这已在 1.20 中修复，我为 1.19 推送了一个新版本，也修复了这个问题 带有大写的旧式 i18n 配置应该在更新后再次工作
At present, I still have a new problem. The name of the creature that is not in the language file will display the English name by default. I tried to add "Caves_Pider", but it didn't work. You can see where the problem is.
![YKQQ ~(9@)WOA Q8(S6(H}E](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/114494454/6ecb708d-06c7-45f9-bcb9-5cbb11b5b39f)
![75(AT)X8949 F4CK_ZMYMFH](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/114494454/9502ec51-e046-4ba5-b7e7-703c500a9d15)

**Comment by wsxiya** [comment]
> > 这已在 1.20 中修复，我为 1.19 推送了一个新版本，也修复了这个问题 带有大写的旧式 i18n 配置应该在更新后再次工作 目前，我还有一个新问题。默认情况下，不在语言文件中的生物名称将显示英文名称。我试图添加“Caves_Pider”，但它不起作用。您可以看到问题所在。
> > ![YKQQ ~（9@）WOA Q8（S6（H}E](https://user-images.githubusercontent.com/114494454/263281611-6ecb708d-06c7-45f9-bcb9-5cbb11b5b39f.png)
> > ![75（AT）X8949 F4CK_ZMYMFH](https://user-images.githubusercontent.com/114494454/263281616-9502ec51-e046-4ba5-b7e7-703c500a9d15.png)

Just downloaded the latest version and it's no problem now, thanks for being able to update, sorry

**Comment by AtomicStryker** [comment]
So it does now work as expected?

**Comment by wsxiya** [comment]
> 所以它现在是否按预期工作？

yes there is no problem now it's great
